repositories {
    mavenCentral()
    google() // Needed for androidx

    maven { url= "https://maven.pedropathing.com/" }
    maven { url = "https://mymaven.bylazar.com/releases" }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:10.3.0'
    implementation 'org.firstinspires.ftc:Blocks:10.3.0'
    implementation 'org.firstinspires.ftc:RobotCore:10.3.0'
    implementation 'org.firstinspires.ftc:RobotServer:10.3.0'
    implementation 'org.firstinspires.ftc:OnBotJava:10.3.0'
    implementation 'org.firstinspires.ftc:Hardware:10.3.0'
    implementation 'org.firstinspires.ftc:FtcCommon:10.3.0'
    implementation 'org.firstinspires.ftc:Vision:10.3.0'

    implementation 'com.pedropathing:ftc:2.0.0'
    implementation 'com.pedropathing:telemetry:0.0.6'
    implementation "com.bylazar:fullpanels:1.0.11"
    implementation "com.bylazar:battery:1.0.3"
    implementation "com.bylazar:camerastream:1.0.0"
    implementation "com.bylazar:capture:1.0.3"
    implementation "com.bylazar:configurables:1.0.5"
    implementation "com.bylazar:field:1.0.6"
    implementation "com.bylazar:gamepad:1.0.4"
    implementation "com.bylazar:graph:1.0.4"
    implementation "com.bylazar:lights:1.0.3"
    implementation "com.bylazar:limelightproxy:1.0.4"
    implementation "com.bylazar:opmodecontrol:1.0.3"
    implementation "com.bylazar:pinger:1.0.3"
    implementation "com.bylazar:telemetry:1.0.5"
    implementation "com.bylazar:themes:1.0.3"
    implementation "com.bylazar:utils:1.0.4"
}

